topology: waxman
num_nodes: 100
p_net_min_size: 50
p_net_max_size: 500
p_net_min_node_resources: 50
p_net_max_node_resources: 100
p_net_min_link_resources: 50
p_net_max_link_resources: 100
num_v_net: 1000
v_net_min_size: 2
v_net_max_size: 10
v_net_min_node_resources: 0
v_net_max_node_resources: 20
v_net_min_link_resources: 0
v_net_max_link_resources: 50
arrival_rate: 0.08
request_avg_lifetime: 500
num_epochs: 30
lr: 0.001
clip_grad: 0.5
weight_decay: 1.0e-05
rl_gamma: 0.99
gae_lambda: 0.98
eps_clip: 0.2
batch_size: 128
target_steps: 256
update_times: 10
entropy_coeff: 0.01
critic_coeff: 0.5
norm_advantage: true
architecture: original
embedding_dim: 128
gcn_num_layers: 3
batch_norm: false
dropout_prob: 0.0
shared_encoder: true
seed: 88
mask_actions: true
reusable: false
eval_interval: 10
save_interval: 10
pretrained_model_path: null
num_iterations: 100
test: load
timeout: 300
heuristic: bw
test_neural: true
test_symbolic: true
test_hybrid: true
save: true
save_dir: save
unique_folder: run_2025-09-30_22h08m30s
verbose: true
device: cuda
